backend:
  name: git-gateway
  repo: ishakuyusufmaina/mcs
  branch: main

media_folder: "images"
public_folder: "/images/"


collections:

  # BLOG POSTS
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    format: "frontmatter"
    output: true
    create: true
    permalink: /posts/:title/
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Body", name: "body", widget: "markdown" }
  # MISC COLLECTION — FORECAST OF EVENTS
  - name: "forecast"
    label: "Forecast of Events"
    folder: "_miscellaneous/forecast"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "PDF File", name: "pdf", widget: "file", allow_multiple: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "miscellaneous" }
      - { label: "Body", name: "body", widget: "markdown" }
  # MISC COLLECTION — NEWSLETTER
  - name: "newsletter"
    label: "Newsletter"
    folder: "_miscellaneous/newsletter"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "PDF File", name: "pdf", widget: "file", allow_multiple: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "miscellaneous" }
      - { label: "Body", name: "body", widget: "markdown" }
  # ---------------------------------------
  # 2. ARTICLES
  # ---------------------------------------
  - name: "articles"
    label: "Articles"
    folder: "_articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Poster Image", name: "poster", widget: "image", required: false }
      - { label: "Poster Alt Text", name: "posterAlt", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        file: "index1.md"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "text" }
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Meta Description", name: "description", widget: "text" }
          - { label: "Main Content", name: "body", widget: "markdown" }
