backend:
  name: git-gateway
  repo: ishakuyusufmaina/mcs
  branch: main

media_folder: "images"
public_folder: "/images/


collections:

  # BLOG POSTS
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Body", name: "body", widget: "markdown" }

  # MISC COLLECTION — FORECAST OF EVENTS
  - name: "forecast"
    label: "Forecast of Events"
    folder: "_miscellaneous/forecast"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "PDF File", name: "pdf", widget: "file", allow_multiple: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "miscellaneous" }
      - { label: "Body", name: "body", widget: "markdown" }

  # MISC COLLECTION — NEWSLETTER
  - name: "newsletter"
    label: "Newsletter"
    folder: "_miscellaneous/newsletter"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "PDF File", name: "pdf", widget: "file", allow_multiple: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "miscellaneous" }
      - { label: "Body", name: "body", widget: "markdown" }
