backend:
  name: github
  repo: ishakuyusufmaina/mcs
  branch: main
 
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: articles
    label: Articles
    folder: "articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }